model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['accuracy']
             )
model.fit(train_batches,
          epochs=15,
          validation_data=test_batches,
          verbose=1,
          shuffle=True)